version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    mongo:
        image: mongo:3.4
        ports:
            - "27017:27017"
        volumes:
            - ./data/db:/data/db'
            - ./data/dump:/dump

    webserver:
        image: puckel/docker-airflow:1.8.1-1
        restart: always
        depends_on:
            - postgres
            - mongo
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - MONGO_URL=mongodb://mongo:27017
        volumes:
            - ./requirements.txt:/requirements.txt
            - ./dags:/usr/local/airflow/dags
            - ./data:/data
            - ./models:/models
            - ./preds:/preds
        ports:
            - "8080:8080"
        command: webserver

    webapp:
        build: ./webapp
        depends_on:
            - mongo
        ports:
            - "5000:5000"
        volumes:
            - ./webapp:/app
        environment:
            - MONGO_URL=mongodb://mongo:27017
